import java.util.*;
import java.util.regex.*;
import java.text.*;
import java.math.*;


public class FoxAndGomoku
{
		public boolean find(String [] board){
		int n = board.length, m = board[0].length();
		for (int i=0;i<n;i++){
			for (int j=0;j<m;j++)
				if (board[i].charAt(j)=='o'){
					if (j+4<m){
						if (board[i].charAt(j+1)=='o'&&board[i].charAt(j+2)=='o'&&board[i].charAt(j+3)=='o'&&board[i].charAt(j+4)=='o')
							return false;
					}
					if (i+4<n){
						if (board[i+1].charAt(j)=='o'&&board[i+2].charAt(j)=='o'&&board[i+3].charAt(j)=='o'&&board[i+4].charAt(j)=='o')
							return false;
					}
					if (i+4<n&&j+4<m){
						if (board[i+1].charAt(j+1)=='o'&&board[i+2].charAt(j+2)=='o'&&board[i+3].charAt(j+3)=='o'&&board[i+4].charAt(j+4)=='o')
							return false;
					}
					if (i+4<n&&j-4>=0)
						if (board[i+1].charAt(j-1)=='o'&&board[i+2].charAt(j-2)=='o'&&board[i+3].charAt(j-3)=='o'&&board[i+4].charAt(j-4)=='o')
							return false;
				}
		}
		return true;
	}
	
	public String win(String[] board)
	{
		if (!find(board))
			return "found";
		else return "not found";
	}
	// BEGIN KAWIGIEDIT TESTING
	// Generated by KawigiEdit 2.1.4 (beta) modified by pivanof
	private static boolean KawigiEdit_RunTest(int testNum, String[] p0, boolean hasAnswer, String p1) {
		System.out.print("Test " + testNum + ": [" + "{");
		for (int i = 0; p0.length > i; ++i) {
			if (i > 0) {
				System.out.print(",");
			}
			System.out.print("\"" + p0[i] + "\"");
		}
		System.out.print("}");
		System.out.println("]");
		FoxAndGomoku obj;
		String answer;
		obj = new FoxAndGomoku();
		long startTime = System.currentTimeMillis();
		answer = obj.win(p0);
		long endTime = System.currentTimeMillis();
		boolean res;
		res = true;
		System.out.println("Time: " + (endTime - startTime) / 1000.0 + " seconds");
		if (hasAnswer) {
			System.out.println("Desired answer:");
			System.out.println("\t" + "\"" + p1 + "\"");
		}
		System.out.println("Your answer:");
		System.out.println("\t" + "\"" + answer + "\"");
		if (hasAnswer) {
			res = answer.equals(p1);
		}
		if (!res) {
			System.out.println("DOESN'T MATCH!!!!");
		} else if ((endTime - startTime) / 1000.0 >= 2) {
			System.out.println("FAIL the timeout");
			res = false;
		} else if (hasAnswer) {
			System.out.println("Match :-)");
		} else {
			System.out.println("OK, but is it right?");
		}
		System.out.println("");
		return res;
	}
	public static void main(String[] args) {
		boolean all_right;
		all_right = true;
		
		String[] p0;
		String p1;
		
		// ----- test 0 -----
		p0 = new String[]{"....o.","...o..","..o...",".o....","o.....","......"};
		p1 = "found";
		all_right = KawigiEdit_RunTest(0, p0, true, p1) && all_right;
		// ------------------
		
		// ----- test 1 -----
		p0 = new String[]{"oooo.",".oooo","oooo.",".oooo","....."};
		p1 = "not found";
		all_right = KawigiEdit_RunTest(1, p0, true, p1) && all_right;
		// ------------------
		
		// ----- test 2 -----
		p0 = new String[]{"oooo.",".oooo","oooo.",".oooo","....o"};
		p1 = "found";
		all_right = KawigiEdit_RunTest(2, p0, true, p1) && all_right;
		// ------------------
		
		// ----- test 3 -----
		p0 = new String[]{"o.....",".o....","..o...","...o..","....o.","......"};
		p1 = "found";
		all_right = KawigiEdit_RunTest(3, p0, true, p1) && all_right;
		// ------------------
		
		// ----- test 4 -----
		p0 = new String[]{"o....","o.o..","o.o.o","o.o..","o...."};
		p1 = "found";
		all_right = KawigiEdit_RunTest(4, p0, true, p1) && all_right;
		// ------------------
		
		// ----- test 5 -----
		p0 = new String[]{"..........","..........","..oooooo..","..o.......","..o.......","..oooooo..",".......o..",".......o..","..oooooo..",".........."};
		p1 = "found";
		all_right = KawigiEdit_RunTest(5, p0, true, p1) && all_right;
		// ------------------
		
		// ----- test 6 -----
		p0 = new String[]{"..........","..........","..oooo.o..","..o.......","..o.......","..o.oooo..",".......o..",".......o..","..oooo.o..",".........."};
		p1 = "not found";
		all_right = KawigiEdit_RunTest(6, p0, true, p1) && all_right;
		// ------------------
		
		// ----- test 7 -----
		p0 = new String[]{"ooooo","ooooo","ooooo","ooooo","ooooo"};
		p1 = "found";
		all_right = KawigiEdit_RunTest(7, p0, true, p1) && all_right;
		// ------------------
		
		// ----- test 8 -----
		p0 = new String[]{".....",".....",".....",".....","....."};
		p1 = "not found";
		all_right = KawigiEdit_RunTest(8, p0, true, p1) && all_right;
		// ------------------
		
		if (all_right) {
			System.out.println("You're a stud (at least on the example cases)!");
		} else {
			System.out.println("Some of the test cases had errors.");
		}
	}
	// END KAWIGIEDIT TESTING
}
//Powered by KawigiEdit 2.1.4 (beta) modified by pivanof!
