import java.util.*;
import java.util.regex.*;
import java.text.*;
import java.math.*;


public class GameInDarknessDiv2
{
	public String check(String[] field, String[] moves)
	{
		
	}
	
	// BEGIN KAWIGIEDIT TESTING
	// Generated by KawigiEdit 2.1.4 (beta) modified by pivanof
	private static boolean KawigiEdit_RunTest(int testNum, String[] p0, String[] p1, boolean hasAnswer, String p2) {
		System.out.print("Test " + testNum + ": [" + "{");
		for (int i = 0; p0.length > i; ++i) {
			if (i > 0) {
				System.out.print(",");
			}
			System.out.print("\"" + p0[i] + "\"");
		}
		System.out.print("}" + "," + "{");
		for (int i = 0; p1.length > i; ++i) {
			if (i > 0) {
				System.out.print(",");
			}
			System.out.print("\"" + p1[i] + "\"");
		}
		System.out.print("}");
		System.out.println("]");
		GameInDarknessDiv2 obj;
		String answer;
		obj = new GameInDarknessDiv2();
		long startTime = System.currentTimeMillis();
		answer = obj.check(p0, p1);
		long endTime = System.currentTimeMillis();
		boolean res;
		res = true;
		System.out.println("Time: " + (endTime - startTime) / 1000.0 + " seconds");
		if (hasAnswer) {
			System.out.println("Desired answer:");
			System.out.println("\t" + "\"" + p2 + "\"");
		}
		System.out.println("Your answer:");
		System.out.println("\t" + "\"" + answer + "\"");
		if (hasAnswer) {
			res = answer.equals(p2);
		}
		if (!res) {
			System.out.println("DOESN'T MATCH!!!!");
		} else if ((endTime - startTime) / 1000.0 >= 2) {
			System.out.println("FAIL the timeout");
			res = false;
		} else if (hasAnswer) {
			System.out.println("Match :-)");
		} else {
			System.out.println("OK, but is it right?");
		}
		System.out.println("");
		return res;
	}
	public static void main(String[] args) {
		boolean all_right;
		all_right = true;
		
		String[] p0;
		String[] p1;
		String p2;
		
		// ----- test 0 -----
		p0 = new String[]{"A.B..","##.##","##.##"};
		p1 = new String[]{"RRDUR"};
		p2 = "Alice wins";
		all_right = KawigiEdit_RunTest(0, p0, p1, true, p2) && all_right;
		// ------------------
		
		// ----- test 1 -----
		p0 = new String[]{"A.B..","##.##","##..."};
		p1 = new String[]{"RRRLD"};
		p2 = "Bob wins";
		all_right = KawigiEdit_RunTest(1, p0, p1, true, p2) && all_right;
		// ------------------
		
		// ----- test 2 -----
		p0 = new String[]{"###.#","###..","A..B#","###..","###.#"};
		p1 = new String[]{"RR","R","UDD"};
		p2 = "Alice wins";
		all_right = KawigiEdit_RunTest(2, p0, p1, true, p2) && all_right;
		// ------------------
		
		// ----- test 3 -----
		p0 = new String[]{"A.###",".B..."};
		p1 = new String[]{"RDRRRLLLLUDUDRLURDLUD"};
		p2 = "Bob wins";
		all_right = KawigiEdit_RunTest(3, p0, p1, true, p2) && all_right;
		// ------------------
		
		// ----- test 4 -----
		p0 = new String[]{".....",".#.#.","##.#.","A###.","B...."};
		p1 = new String[]{"D"};
		p2 = "Alice wins";
		all_right = KawigiEdit_RunTest(4, p0, p1, true, p2) && all_right;
		// ------------------
		
		// ----- test 5 -----
		p0 = new String[]{".#...#....#.......#....#......","...###.#.#..#.#.#..###...#.#.#",".#.#...#...#..#..#.....##.#...","#..#.##..##..#.#..###.#....#.#","..#..#..#...#...#....#..##.#..","#..##..#..##.#.#.####..#.#...#",".#....##.#.....#......##.#.#..",".###.#...#.#.#..#.#.##...##.#.",".....#.#.##..#.#..##...##...#.","#.#.#...#...#.#.#...#.#.#.##.#",".#..##.#..##..#.###...........","..##.....####.......##.#.#.##.","#....##.#.#...####.#...#.#.#..","#.#.#......##.#...#..#.#..#..#","..#..#.#.##...#.#..#..#..#..#.",".#..#...#...#..#..#.#..#..#A#.","..#..#.#.B##.##..#...#.#.##...","#.#.##..#......#.#.#.#.#...#.#","#.#...#.######...#.#.#.#.#.#..","..#.##.#.....#.##..#...#.#.#.#",".#..#..#.#.#.#.#..#.#####..#.#","..#.#.##.#.#.##.#......#..#...","#..#.....#.#.....#.#.##..##.#.","##..###.#..#.#.#.#..##..#...##","##.#...#..##.#.#..#.#..#.#.#..","#..#.#.####..#..#..#..#......#","..#..#.....####..#.##.#.###.#.",".#..#.####.#.#..#.....#...#...","..##.......#...#..####.##.#.#.","#....#.#.#..#.###....#....#..#"};
		p1 = new String[]{"UURURUULLLLLLLLLLDLLLLUDLLUDDLRDDDULLDLLDDRRRRRDDU","RRUUURUULLD"};
		p2 = "Alice wins";
		all_right = KawigiEdit_RunTest(5, p0, p1, true, p2) && all_right;
		// ------------------
		
		if (all_right) {
			System.out.println("You're a stud (at least on the example cases)!");
		} else {
			System.out.println("Some of the test cases had errors.");
		}
	}
	// END KAWIGIEDIT TESTING
}
//Powered by KawigiEdit 2.1.4 (beta) modified by pivanof!
